### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by xbxct** [ITsMrToad/PalladiumMod#28]
Pojav Glow·Worm crash report
 - Time: 17 сент. 2024 г. 12:18:46
 - Device: rain_ru 220333QNY
 - Android version: 13
 - Crash stack trace:
 - Launcher version: fuchsia-20240908-b2713db-main_v3
java.lang.NullPointerException: Attempt to read from field 'java.util.Map net.kdt.pojavlaunch.value.launcherprofiles.MinecraftLauncherProfiles.profiles' on a null object reference in method 'net.kdt.pojavlaunch.value.launcherprofiles.MinecraftProfile net.kdt.pojavlaunch.fragments.ProfileEditorFragment.getProfile(java.lang.String)'
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.getProfile(ProfileEditorFragment.java:181)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.loadValues(ProfileEditorFragment.java:145)
	at net.kdt.pojavlaunch.fragments.ProfileEditorFragment.onViewCreated(ProfileEditorFragment.java:140)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at net.kdt.pojavlaunch.LauncherActivity.onStart(LauncherActivity.java:263)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1566)
	at android.app.Activity.performStart(Activity.java:8572)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3934)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by ITsMrToad** [comment]
Palladium don't support PoJav.

**Comment by xbxct** [comment]
No matter

**Comment by ITsMrToad** [comment]
> Palladium don't support PoJav.

That means I will NOT be answering this question and others like it.
