### ISSUE TITLE
Crash in game

### ISSUE THREAD

**Issue by xbxct** [ITsMrToad/PalladiumMod#32]
---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 2024-09-18 22:36:04
Description: Exception in server tick loop

java.lang.IllegalAccessError: failed to access class net.minecraft.class_1493$class_1494 from class com.mr_toad.palladium.common.entity.map.AvoidGoalMapperProvider (net.minecraft.class_1493$class_1494 and com.mr_toad.palladium.common.entity.map.AvoidGoalMapperProvider are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @79ca92b9)
	at com.mr_toad.palladium.common.entity.map.AvoidGoalMapperProvider.replaceAvoidsWolf(AvoidGoalMapperProvider.java:73)
	at com.mr_toad.palladium.common.entity.map.AvoidGoalMapperProvider.run(AvoidGoalMapperProvider.java:31)
	at com.mr_toad.palladium.api.GoalMapperProvider.runIfCan(GoalMapperProvider.java:26)
	at com.mr_toad.palladium.common.entity.processor.EntityAiMappingProcessor.lambda$static$0(EntityAiMappingProcessor.java:14)
	at com.mr_toad.palladium.common.entity.processor.EntityAiMappingProcessors.process(EntityAiMappingProcessors.java:30)
	at com.mr_toad.palladium.core.Palladium.lambda$onInitialize$0(Palladium.java:11)
	at net.fabricmc.fabric.api.networking.v1.EntityTrackingEvents.lambda$static$0(EntityTrackingEvents.java:36)
	at net.minecraft.class_3231.handler$blg000$fabric-networking-api-v1$onStartTracking(class_3231.java:1040)
	at net.minecraft.class_3231.method_18760(class_3231.java)
	at net.minecraft.class_3898$class_3208.method_18736(class_3898.java:1449)
	at net.minecraft.class_3898.method_18713(class_3898.java:1100)
	at net.minecraft.class_3215.method_14096(class_3215.java:473)
	at net.minecraft.class_3244.method_12063(class_3244.java:999)
	at net.minecraft.class_2828.method_12272(class_2828.java:114)
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:16)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:7818)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_18857(class_1255.java:139)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by xbxct** [comment]
![Screenshot_2024-09-18-22-48-51-890_net kdt pojavlaunch firefly](https://github.com/user-attachments/assets/63e4c68d-8cf8-474f-9b6e-2ed62c43c858)
There are also no stars

**Comment by xbxct** [comment]
Cats and stars are not palladium's fault. Cats become like that after the first squat.

**Comment by ITsMrToad** [comment]
See [29](https://github.com/ITsMrToad/PalladiumMod/issues/29)
