### ISSUE TITLE
Crash when loading a world and shaders are enabled

### ISSUE THREAD

**Issue by k0nstruct** [ITsMrToad/PalladiumMod#39]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Quilt

### Describe the bug

When I load a world with shaders disabled, it loads fine. I can then enable shaders in iris, and it works.

But when I load the same world with shaders enabled, it will crash the game, with this log: 
---- Crashed! ----
Date/Time: 2024/09/25 16:08:10.9971 [+0200]
Quilt Loader Version: 0.26.4

```
-- Crash --

org.quiltmc.loader.impl.FormattedException: org.quiltmc.loader.impl.discovery.ModResolutionException: Failed to create the transform bundle!
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:309)
	at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:78)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: org.quiltmc.loader.impl.discovery.ModResolutionException: Failed to create the transform bundle!
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.createTransformCache(TransformCacheManager.java:280)
	at org.quiltmc.loader.impl.transformer.TransformCacheManager.populateTransformBundle(TransformCacheManager.java:105)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.setup(QuiltLoaderImpl.java:378)
	at org.quiltmc.loader.impl.QuiltLoaderImpl.load(QuiltLoaderImpl.java:307)
	... 3 more
```

### Steps to reproduce

Start your world with shaders already enabled. If you start with them disabled, it works, and you can toggle them back on after.
It's just an inconvenience, but I hope it can be fixed.

### What version of the palladium are you using?

1.0.7/1.20.1

**Comment by ITsMrToad** [comment]
Send full log
