### ISSUE TITLE
Crash on fabric beta 1.0.9.2-1.21.1

### ISSUE THREAD

**Issue by VicoIlFico** [ITsMrToad/PalladiumMod#56]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

This is what the fabric modloader error looks like:

Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Palladium' (palladium) 1.0.9.2 with any version that is compatible with:
		 - minecraft 1.21.1
More details:
	 - Mod 'Palladium' (palladium) 1.0.9.2 requires version 1.1.1 or later of toadlib-fabric, which is missing!
	 - Mod 'Palladium' (palladium) 1.0.9.2 requires any version between 1.20 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

And this is what the console is showing me: 

[13/10/2024 19:03:44 PM] Organising filesystem
[13/10/2024 19:03:44 PM] ATLauncher Version: 3.4.37.3 [10af587dd8b2f6e7d8d4993620fce0875b34d84b]
[13/10/2024 19:03:44 PM] App Arguments: []
[13/10/2024 19:03:44 PM] JVM Arguments: ["-Djna.nosys=true","-Djava.net.preferIPv4Stack=true","-Dawt.useSystemAAFontSettings=on","-Dswing.aatext=true"]
[13/10/2024 19:03:44 PM] Java Version: Java 17 (17.0.9)
[13/10/2024 19:03:44 PM] Java Path: C:\Users\Desktop-Ale\Desktop\graalvm-jdk-23+37.1
[13/10/2024 19:03:44 PM] 64 Bit Java: true
[13/10/2024 19:03:44 PM] RAM Available: 16250MB
[13/10/2024 19:03:44 PM] Launcher Directory: **USERSDIR**
[13/10/2024 19:03:45 PM] GPU: NVIDIA GeForce RTX 3060 Ti (NVIDIA (0x10de)) DriverVersion=32.0.15.6094 4095MB VRAM
[13/10/2024 19:03:45 PM] CPU: 11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz 8 cores/16 threads
[13/10/2024 19:03:45 PM] Operating System: Windows (11 build 22631)
[13/10/2024 19:03:45 PM] Bitness: 64
[13/10/2024 19:03:45 PM] Uptime: 10250
[13/10/2024 19:03:45 PM] Manufacturer: Microsoft
[13/10/2024 19:03:45 PM] Showing splash screen and loading everything
[13/10/2024 19:03:45 PM] Checking for updated files!
[13/10/2024 19:03:46 PM] Launcher finished loading everything
[13/10/2024 19:03:46 PM] Launcher opening
[13/10/2024 19:03:46 PM] Made By Bob*
[13/10/2024 19:03:46 PM] *(Not Actually)
[13/10/2024 19:03:46 PM] Setting up Bottom Bar
[13/10/2024 19:03:46 PM] Finished Setting up Bottom Bar
[13/10/2024 19:03:46 PM] Setting up Tabs
[13/10/2024 19:03:46 PM] Finished Setting up Tabs
[13/10/2024 19:03:46 PM] Showing Launcher
[13/10/2024 19:03:49 PM] Preparing for launch!
[13/10/2024 19:03:53 PM] Launching pack Minecraft 1.21.1 (Vanilla) for Minecraft 1.21.1
[13/10/2024 19:03:53 PM] Logging into Minecraft!
[13/10/2024 19:03:53 PM] Using Java runtime java-runtime-delta (Java 21.0.3) at path **USERSDIR**\runtimes\minecraft\java-runtime-delta\windows-x64\java-runtime-delta
[13/10/2024 19:03:53 PM] Loader: Fabric 0.16.7
[13/10/2024 19:03:53 PM] Mods:
[13/10/2024 19:03:53 PM]  - \BadOptimizations-2.1.4-1.21.jar (Added)
[13/10/2024 19:03:53 PM]  - \cloth-config-15.0.140-fabric.jar (Added)
[13/10/2024 19:03:53 PM]  - \enhancedblockentities-0.10.2+1.21.jar (Added)
[13/10/2024 19:03:53 PM]  - \entityculling-fabric-1.7.0-mc1.21.jar (Added)
[13/10/2024 19:03:53 PM]  - \fabric-api-0.105.0+1.21.1.jar (Added)
[13/10/2024 19:03:53 PM]  - \fasterrandom-5.1.0.jar (Added)
[13/10/2024 19:03:53 PM]  - \ferritecore-7.0.0-fabric.jar (Added)
[13/10/2024 19:03:53 PM]  - \GpuTape-1.18x-1.21x-1.0.3.jar (Added)
[13/10/2024 19:03:53 PM]  - \lithium-fabric-mc1.21.1-0.13.1.jar (Added)
[13/10/2024 19:03:53 PM]  - \modernfix-fabric-5.19.3+mc1.21.1.jar (Added)
[13/10/2024 19:03:53 PM]  - \modmenu-11.0.2.jar (Added)
[13/10/2024 19:03:53 PM]  - \Moonrise-Fabric-0.1.0-beta.4+e244c60.jar (Added)
[13/10/2024 19:03:53 PM]  - \noisium-fabric-2.3.0+mc1.21-1.21.1.jar (Added)
[13/10/2024 19:03:53 PM]  - \Palladium-1.21x-1.0.9.2.jar (Added)
[13/10/2024 19:03:53 PM]  - \placeholder-api-2.4.1+1.21.jar (Added)
[13/10/2024 19:03:53 PM]  - \ShieldStatus-1.21.jar (Added)
[13/10/2024 19:03:53 PM]  - \ToadLib-1.21x-1.1.6.jar (Added)
[13/10/2024 19:03:53 PM]  - \VulkanMod_1.21-0.5.0.jar (Added)
[13/10/2024 19:03:53 PM]  - \WalksyCompleteShieldFixes-1.21.jar (Added)
[13/10/2024 19:03:53 PM] Launching Minecraft with the following arguments (user related stuff has been removed): [USERSDIR\runtimes\minecraft\java-runtime-delta\windows-x64\java-runtime-delta\bin\javaw, -Xmx4096M, -XX:MetaspaceSize=1024M, -Duser.language=en, -Duser.country=US, -Dfml.log.level=INFO, -Dlog4j.configurationFile=USERSDIR\assets\log_configs\client-1.12.xml, -XX:+UnlockExperimentalVMOptions, -XX:+UnlockDiagnosticVMOptions, -XX:+AlwaysActAsServerClassMachine, -XX:+AlwaysPreTouch, -XX:+DisableExplicitGC, -XX:NmethodSweepActivity=1, -XX:ReservedCodeCacheSize=400M, -XX:NonNMethodCodeHeapSize=12M, -XX:ProfiledCodeHeapSize=194M, -XX:NonProfiledCodeHeapSize=194M, -XX:-DontCompileHugeMethods, -XX:+PerfDisableSharedMem, -XX:+UseFastUnorderedTimeStamps, -XX:+UseCriticalJavaThreadPriority, -XX:+EagerJVMCI, -Dgraal.TuneInlinerExploration=1, -XX:+UseG1GC, -XX:MaxGCPauseMillis=37, -XX:+PerfDisableSharedMem, -XX:G1HeapRegionSize=16M, -XX:G1NewSizePercent=23, -XX:G1ReservePercent=20, -XX:SurvivorRatio=32, -XX:G1MixedGCCountTarget=3, -XX:G1HeapWastePercent=20, -XX:InitiatingHeapOccupancyPercent=10, -XX:G1RSetUpdatingPauseTimePercent=0, -XX:MaxTenuringThreshold=1, -XX:G1SATBBufferEnqueueingThresholdPercent=30, -XX:G1ConcMarkStepDurationMillis=5.0, -XX:GCTimeRatio=99, -XX:G1ConcRefinementServiceIntervalMillis=150, -XX:G1ConcRSHotCardLimit=16, -XX:AllocatePrefetchStyle=3, -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xss1M, -Djava.library.path=USERSDIR\temp\natives-31a1e85a12e7478597ee59f9840ecb6f, -Djna.tmpdir=USERSDIR\temp\natives-31a1e85a12e7478597ee59f9840ecb6f, -Dorg.lwjgl.system.SharedLibraryExtractPath=USERSDIR\temp\natives-31a1e85a12e7478597ee59f9840ecb6f, -Dio.netty.native.workdir=USERSDIR\temp\natives-31a1e85a12e7478597ee59f9840ecb6f, -Dminecraft.launcher.brand=ATLauncher, -Dminecraft.launcher.version=3.4.37.3, -cp, USERSDIR\libraries\org\ow2\asm\asm\9.7.1\asm-9.7.1.jar;USERSDIR\libraries\org\ow2\asm\asm-analysis\9.7.1\asm-analysis-9.7.1.jar;USERSDIR\libraries\org\ow2\asm\asm-commons\9.7.1\asm-commons-9.7.1.jar;USERSDIR\libraries\org\ow2\asm\asm-tree\9.7.1\asm-tree-9.7.1.jar;USERSDIR\libraries\org\ow2\asm\asm-util\9.7.1\asm-util-9.7.1.jar;USERSDIR\libraries\net\fabricmc\sponge-mixin\0.15.3+mixin.0.8.7\sponge-mixin-0.15.3+mixin.0.8.7.jar;USERSDIR\libraries\net\fabricmc\intermediary\1.21.1\intermediary-1.21.1.jar;USERSDIR\libraries\net\fabricmc\fabric-loader\0.16.7\fabric-loader-0.16.7.jar;USERSDIR\libraries\com\github\oshi\oshi-core\6.4.10\oshi-core-6.4.10.jar;USERSDIR\libraries\com\google\code\gson\gson\2.10.1\gson-2.10.1.jar;USERSDIR\libraries\com\google\guava\failureaccess\1.0.1\failureaccess-1.0.1.jar;USERSDIR\libraries\com\google\guava\guava\32.1.2-jre\guava-32.1.2-jre.jar;USERSDIR\libraries\com\ibm\icu\icu4j\73.2\icu4j-73.2.jar;USERSDIR\libraries\com\mojang\authlib\6.0.54\authlib-6.0.54.jar;USERSDIR\libraries\com\mojang\blocklist\1.0.10\blocklist-1.0.10.jar;USERSDIR\libraries\com\mojang\brigadier\1.3.10\brigadier-1.3.10.jar;USERSDIR\libraries\com\mojang\datafixerupper\8.0.16\datafixerupper-8.0.16.jar;USERSDIR\libraries\com\mojang\logging\1.2.7\logging-1.2.7.jar;USERSDIR\libraries\com\mojang\patchy\2.2.10\patchy-2.2.10.jar;USERSDIR\libraries\com\mojang\text2speech\1.17.9\text2speech-1.17.9.jar;USERSDIR\libraries\commons-codec\commons-codec\1.16.0\commons-codec-1.16.0.jar;USERSDIR\libraries\commons-io\commons-io\2.15.1\commons-io-2.15.1.jar;USERSDIR\libraries\commons-logging\commons-logging\1.2\commons-logging-1.2.jar;USERSDIR\libraries\io\netty\netty-buffer\4.1.97.Final\netty-buffer-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-codec\4.1.97.Final\netty-codec-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-common\4.1.97.Final\netty-common-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-handler\4.1.97.Final\netty-handler-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-resolver\4.1.97.Final\netty-resolver-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-transport-classes-epoll\4.1.97.Final\netty-transport-classes-epoll-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-transport-native-unix-common\4.1.97.Final\netty-transport-native-unix-common-4.1.97.Final.jar;USERSDIR\libraries\io\netty\netty-transport\4.1.97.Final\netty-transport-4.1.97.Final.jar;USERSDIR\libraries\it\unimi\dsi\fastutil\8.5.12\fastutil-8.5.12.jar;USERSDIR\libraries\net\java\dev\jna\jna-platform\5.14.0\jna-platform-5.14.0.jar;USERSDIR\libraries\net\java\dev\jna\jna\5.14.0\jna-5.14.0.jar;USERSDIR\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;USERSDIR\libraries\org\apache\commons\commons-compress\1.26.0\commons-compress-1.26.0.jar;USERSDIR\libraries\org\apache\commons\commons-lang3\3.14.0\commons-lang3-3.14.0.jar;USERSDIR\libraries\org\apache\httpcomponents\httpclient\4.5.13\httpclient-4.5.13.jar;USERSDIR\libraries\org\apache\httpcomponents\httpcore\4.4.16\httpcore-4.4.16.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-api\2.22.1\log4j-api-2.22.1.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-core\2.22.1\log4j-core-2.22.1.jar;USERSDIR\libraries\org\apache\logging\log4j\log4j-slf4j2-impl\2.22.1\log4j-slf4j2-impl-2.22.1.jar;USERSDIR\libraries\org\jcraft\jorbis\0.0.17\jorbis-0.0.17.jar;USERSDIR\libraries\org\joml\joml\1.10.5\joml-1.10.5.jar;USERSDIR\libraries\org\lwjgl\lwjgl-freetype\3.3.3\lwjgl-freetype-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-freetype\3.3.3\lwjgl-freetype-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-freetype\3.3.3\lwjgl-freetype-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-freetype\3.3.3\lwjgl-freetype-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.3.3\lwjgl-glfw-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.3.3\lwjgl-glfw-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.3.3\lwjgl-glfw-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-glfw\3.3.3\lwjgl-glfw-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.3.3\lwjgl-jemalloc-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.3.3\lwjgl-jemalloc-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.3.3\lwjgl-jemalloc-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-jemalloc\3.3.3\lwjgl-jemalloc-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.3.3\lwjgl-openal-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.3.3\lwjgl-openal-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.3.3\lwjgl-openal-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-openal\3.3.3\lwjgl-openal-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.3.3\lwjgl-opengl-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.3.3\lwjgl-opengl-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.3.3\lwjgl-opengl-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-opengl\3.3.3\lwjgl-opengl-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.3.3\lwjgl-stb-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.3.3\lwjgl-stb-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.3.3\lwjgl-stb-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-stb\3.3.3\lwjgl-stb-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.3.3\lwjgl-tinyfd-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.3.3\lwjgl-tinyfd-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.3.3\lwjgl-tinyfd-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl-tinyfd\3.3.3\lwjgl-tinyfd-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.3.3\lwjgl-3.3.3.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.3.3\lwjgl-3.3.3-natives-windows.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.3.3\lwjgl-3.3.3-natives-windows-arm64.jar;USERSDIR\libraries\org\lwjgl\lwjgl\3.3.3\lwjgl-3.3.3-natives-windows-x86.jar;USERSDIR\libraries\org\lz4\lz4-java\1.8.0\lz4-java-1.8.0.jar;USERSDIR\libraries\org\slf4j\slf4j-api\2.0.9\slf4j-api-2.0.9.jar;USERSDIR\libraries\net\minecraft\client\1.21.1\client-1.21.1.jar, -DFabricMcEmu= net.minecraft.client.main.Main , net.fabricmc.loader.impl.launch.knot.KnotClient, --username, REDACTED, --version, 1.21.1, --gameDir, USERSDIR\instances\Minecraft1211withFabric, --assetsDir, USERSDIR\assets, --assetIndex, 17, --uuid, REDACTED, --accessToken, REDACTED, --userType, msa, --versionType, release, --width=2048, --height=1152]
[13/10/2024 19:03:53 PM] OpenJDK 64-Bit Server VM warning: Ignoring option G1ConcRefinementServiceIntervalMillis; support was removed in 20.0
[13/10/2024 19:03:53 PM] OpenJDK 64-Bit Server VM warning: Ignoring option G1ConcRSHotCardLimit; support was removed in 21.0
[13/10/2024 19:03:53 PM] [main/INFO] Loading Minecraft 1.21.1 with Fabric Loader 0.16.7
[13/10/2024 19:03:54 PM] [main/WARN] Mod resolution failed
[13/10/2024 19:03:54 PM] [main/INFO] Immediate reason: [HARD_DEP_NO_CANDIDATE palladium 1.0.9.2 {depends toadlib-fabric @ [>=1.1.1]}, ROOT_FORCELOAD_SINGLE palladium 1.0.9.2]
[13/10/2024 19:03:54 PM] [main/INFO] Reason: [HARD_DEP palladium 1.0.9.2 {depends toadlib-fabric @ [>=1.1.1]}, HARD_DEP palladium 1.0.9.2 {depends minecraft @ [~1.20]}]
[13/10/2024 19:03:54 PM] [main/INFO] Fix: add [], remove [], replace [[palladium 1.0.9.2] -> add:palladium 1 ([(-âˆž,âˆž)])]
[13/10/2024 19:03:54 PM] A potential solution has been determined, this may resolve your problem:
[13/10/2024 19:03:54 PM] 	 - Replace mod 'Palladium' (palladium) 1.0.9.2 with any version that is compatible with:
[13/10/2024 19:03:54 PM] 		 - minecraft 1.21.1
[13/10/2024 19:03:54 PM] More details:
[13/10/2024 19:03:54 PM] 	 - Mod 'Palladium' (palladium) 1.0.9.2 requires version 1.1.1 or later of toadlib-fabric, which is missing!
[13/10/2024 19:03:54 PM] 	 - Mod 'Palladium' (palladium) 1.0.9.2 requires any version between 1.20 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
[13/10/2024 19:03:54 PM] 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
[13/10/2024 19:03:54 PM] 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:196)
[13/10/2024 19:03:54 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
[13/10/2024 19:03:54 PM] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
[13/10/2024 19:03:54 PM] 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13/10/2024 19:03:54 PM] [main/ERROR] Incompatible mods found!
[13/10/2024 19:06:15 PM] Copied Log to clipboard

Keep in mind I'm using other optimization mods and non-default jvm and java flags, but this issue doesn't occur in Palladium stable release 1.0.9-1.21.1 fabric. I'm using ATlauncher and the latest current versions of every mod shown in this log.

### Steps to reproduce

Update to Palladium 1.0.9.2-1.21.1 Fabric, launch Minecraft. Immediate startup crash. Doesn't occur in prior versions

### What version of the palladium are you using?

1.0.9.2-1.21.1 Fabric

**Comment by VicoIlFico** [comment]
It looks to me like the problem is the mod doesn't recognize toadlib is installed and doesn't support the Minecraft version it's made for

**Comment by ITsMrToad** [comment]
Does it happen without any other mods?

**Comment by Emulond** [comment]
> It looks to me like the problem is the mod doesn't recognize toadlib is installed and doesn't support the Minecraft version it's made for

I have the same issue here. It's really embarrassing.

**Comment by VicoIlFico** [comment]
> Does it happen without any other mods?

Just tried it and yes, it does

**Comment by ITsMrToad** [comment]
Is 1.0.9.3 working? Right now, on my own, I can't test this.....

**Comment by VicoIlFico** [comment]
> Is 1.0.9.3 working? Right now, on my own, I can't test this.....

It doesnt show the update on my launcher, might be cause it was a few minutes ago. Anyway i tried it by downloading it from modrinth but it still crashes on launch, atleast now it only says toadlib is missing though. Also why does it say it requires iris shaders?

**Comment by Emulond** [comment]
> Is 1.0.9.3 working?

I'd need a Fabric version to confirm, comrade. Can't you compile?

**Comment by VicoIlFico** [comment]
> I'd need a Fabric version to confirm, comrade. Can't you compile?

he just uploaded one https://modrinth.com/mod/mpalladium/version/1.0.9.3-1.20-1.20-4-Fabric

**Comment by Emulond** [comment]
> he just uploaded one https://modrinth.com/mod/mpalladium/version/1.0.9.3-1.20-1.20-4-Fabric

That's not for 1.21.1, damn it. It's literally present for all 1.21.1 loaders except for Fabric.

**Comment by VicoIlFico** [comment]
> That's not for 1.21.1, damn it.

it is look on the right. also doesnt say the wrong version of minecraft is present anymore

**Comment by Emulond** [comment]
> it is look on the right. also doesnt say the wrong version of minecraft is present anymore

What in the world are you talking about look at your own link. It ends with "1.20.4". With primitive human capability of vision you can determine it. It's not present. I'm retrieving information in realtime on Modrinth platform. 

1.21.1 support is present only for other loaders than Fabric. Check by yourself. These are for NeoForge and Forge. Not Fabric.

**Comment by ITsMrToad** [comment]
I uploaded wrong version.....
Here [1.21x-Fabric](https://modrinth.com/mod/mpalladium/version/1.0.9.3-1.21x-Fabric)
Try it and let me know if it works...

**Comment by VicoIlFico** [comment]
> I uploaded wrong version..... Here [1.21x-Fabric](https://modrinth.com/mod/mpalladium/version/1.0.9.3-1.21x-Fabric) Try it and let me know if it works...

same issue

**Comment by ITsMrToad** [comment]
Continued... [1.0.9.4](https://modrinth.com/mod/mpalladium/version/1.0.9.4-1.21x-Fabric) is out.

**Comment by Emulond** [comment]
> Continued... 1.0.9.4 is out.

Splendid, tovarisch! Works like a charm. 1.21.1 Fabric here.

**Comment by VicoIlFico** [comment]
> Continued... [1.0.9.4] 

It doesn't crash at launch now but id still rather not use it until you can properly test it yourself and release a stable version

**Comment by ITsMrToad** [comment]
> It doesn't crash at launch now but id still rather not use it until you can properly test it yourself and release a stable version

I'm afraid there won't be a stable version for a long time.
My main computer is being repaired, and my current one is a bucket of nuts that can't even run minecraft...

If the version doesn't get bug reports, I'll change its channel to release
