### ISSUE TITLE
Crash when opening grave

### ISSUE THREAD

**Issue by Hitaxas** [ITsMrToad/PalladiumMod#61]
### What operating systems are you seeing the problem on?

Windows

### What the loader are you seeing the problem on?

Fabric

### Describe the bug

With this mod, opening a grave from [Universal graves](https://modrinth.com/mod/universal-graves) causes the client to crash. 
[CrashLog.txt](https://github.com/user-attachments/files/17502955/CrashLog.txt)

### What version of the palladium are you using?

1.0.9.2-1.20-1.20-4-Fabric

**Comment by ITsMrToad** [comment]
Maybe I missed something, but the log doesn't mention palladium or universal graves, only ip_next.

**Comment by Hitaxas** [comment]
> java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.value()'
	at net.minecraft.class_2487.palladium$getTexturesPayload(class_2487.java:1716)
	at net.minecraft.class_2487.palladium$getSkin(class_2487.java:1707)
	at net.minecraft.class_2487.redirect$hoc000$palladium$areTagMapsEqual(class_2487.java:1699)
	at net.minecraft.class_2487.equals(class_2487.java:471)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:169)
	at org.anti_ad.mc.ipnext.item.ItemType.equals(Unknown Source)
	at kotlin.jvm.internal.Intrinsics.areEqual(Intrinsics.java:169)
	at org.anti_ad.mc.ipnext.event.SlotHighlightHandler.getSlotLocations(Unknown Source)
	at org.anti_ad.mc.ipnext.event.SlotHighlightHandler.drawSprite(Unknown Source)
	at org.anti_ad.mc.ipnext.event.SlotHighlightHandler.drawForeground(Unknown Source)
	at org.anti_ad.mc.ipnext.specific.event.PLockSlotHandler$DefaultImpls.onForegroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.event.SlotHighlightHandler.onForegroundRender(Unknown Source)
	at org.anti_ad.mc.ipnext.gui.inject.ContainerScreenEventHandler.onForegroundRender(Unknown Source)
	at net.minecraft.class_465.handler$fjg000$inventoryprofilesnext$onForegroundRender(class_465.java)
	at net.minecraft.class_465.method_25394(class_465.java:129)
	at net.minecraft.class_476.method_25394(class_476.java:28)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I see 3 references to palladium at the top of the list in that log I had sent. The second, third and forth lines. It's possible it's actually a compat error with ipn, but it only happens when opening a grave in that case, and doesn't happen when opening player inventory or a anything else that has an inventory, like a chest.
